version: '3.1'
services:
  balance-exporter:
    restart: always
    build: .
    ports:
      - 9102:9102
    user: "pptr:pptr"
    cap_add:
      - SYS_ADMIN
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
    volumes:
      - ./config.toml:/app/config.toml
      - ./plugins:/app/plugins
      - ./screenshot:/app/screenshot:rw
